## Site Settings - 기본정보
##############################
text_skin: default
highlight_theme: tomorrow-night-eighties
url     : https://yourbuoy.kr
baseurl : /

title   : 직장생활표류기
tagline: 직장에서 표류중인 당신을 구할 부표
description: 직장생활에 왕도는 없지만 요령은 있다. 멘붕을 줄여줄 업무팁, 멘탈관리법을 공유합니다.


## Language and Timezone
##############################
lang: ko
timezone: Asia/Seoul


## Author & Social
##############################
author:
  type      : person
  name      : Buoy
  url       : https://yourbuoy.kr
  avatar    : # path or url of avatar image (square)
  bio       : # I am an amazing person.
  email     : riverpurple7@gmail.com

  facebook  : yourbuoy_kr
  twitter   : yourbuoy_kr
  medium    :
  linkedin  :
  github    : yourbuoy


## GitHub Repository
##############################
repository: BoraKang/yourbuoy
repository_tree: master


## Paths - 여기 잘 모르겠음
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## Post
##############################
## excerpt - 자동 본문발췌 구분점
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

# TOC(Table of Contents)- 헤딩에 보여줄 요소
toc:
  selectors: "h1,h2,h3"

## Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: # false (default), true


## Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## Sources
##############################
sources: # bootcdn (default), unpkg


## Sharing - 공유플러그인
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## Comments - 댓글시스템 공급
##############################
comments:
  provider: "disqus" # "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: yourbuoy


## Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## Analytics
##############################
analytics:
  provider:  google

  ## Google Analytics
  google:
    tracking_id : UA-147384946-1 # Google Analytics id for the site
    anonymize_ip: true # Anonymize IP tracking for Analytics


## Build
##############################
markdown    : kramdown #markdown개조판
highlighter : rouge #syntax heilighter
permalink   : /:categories/:title/

# Jekyll 컴파일 시, destination에 필요없는 것들 명시
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /test
  - /vendor

## Post default - 포스트 레이아웃 기본값 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: false
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true
      key: anything
      mode: immersive #헤더 모드
      header:
        theme: dark
      article_header:
        type: overlay # 포스트 내부헤더 오버레이 적용여부
        theme: dark
        background_color: '#203028'

## Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
